apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: web
spec:
  containers:
    - name: nginx-container
      image: nginx
      command: ['nginx']
      args: ['-g', 'daemon off;', '-q']
      ports:
        - containerPort: 80
