apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - args:
    - ls
    image: nginx
    imagePullPolicy: IfNotPresent
    name: nginx
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: 2019-08-01T18:33:03Z
    labels:
      run: nginx
    name: nginx
    namespace: default
    resourceVersion: "3349974"
    selfLink: /api/v1/namespaces/default/pods/nginx
    uid: cc60d6d7-b48a-11e9-b2f4-025000000001
  spec:
    containers:
    - image: nginx
      imagePullPolicy: IfNotPresent
      name: nginx
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: default-token-jd8nc
        readOnly: true
    dnsPolicy: ClusterFirst
    nodeName: docker-for-desktop
    restartPolicy: Never
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: default-token-jd8nc
      secret:
        defaultMode: 420
        secretName: default-token-jd8nc
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: 2019-08-01T18:33:04Z
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: 2019-08-01T18:33:06Z
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: 2019-08-01T18:33:04Z
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: docker://b1fe1086c2fbc74fb1f8f96b395ef0a24ce15ba4daef52d6a0e6e2dcc012cc8f
      image: nginx:latest
      imageID: docker-pullable://nginx@sha256:eb3320e2f9ca409b7c0aa71aea3cf7ce7d018f03a372564dbdb023646958770b
      lastState: {}
      name: nginx
      ready: true
      restartCount: 0
      state:
        running:
          startedAt: 2019-08-01T18:33:05Z
    hostIP: 192.168.65.3
    phase: Running
    podIP: 10.1.9.56
    qosClass: BestEffort
    startTime: 2019-08-01T18:33:04Z
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
