apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busy
  name: busy
spec:
  containers:
  - args:
    - sh
    - -c
    - sleep 3600
    image: busybox
    imagePullPolicy: IfNotPresent
    name: busy-1
    resources: {}
    volumeMounts:
    - name: my-volume
      mountPath: /etc/foo
  - args:
    - sh
    - -c
    - sleep 3600
    image: busybox
    imagePullPolicy: IfNotPresent
    name: busy-2
    resources: {}
    volumeMounts:
    - name: my-volume
      mountPath: /etc/foo
  volumes:
  - name: my-volume
    emptyDir: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
