apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: bbox
  name: bbox
spec:
  volumes:
    - name: my-volume
      persistentVolumeClaim:
        claimName: mypvc
  containers:
  - args:
    - /bin/sh
    - -c
    - sleep 3600
    image: busybox
    imagePullPolicy: IfNotPresent
    name: bbox
    resources: {}
    volumeMounts: 
      - mountPath: "/etc/foo"
        name: my-volume
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
