apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
  command:
  - sh
  - sleep 3600
  - exit
  - name: bbox1
    image: busybox
    command:
    - sh
    - sleep 3600
    - exit
    volumeMounts:
    - name: my-mount
      mountPath: /etc/foo
  volumes:
  - name: my-volume
    emptyDir: {}
