apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
    environment: prod
  name: nginx
spec:
  securityContext:
    runAsUser: 101
  containers:
  - image: nginx
    imagePullPolicy: IfNotPresent
    name: nginx
    readinessProbe:
      httpGet:
        port: 80
        path: /
    livenessProbe:
      exec:
        command:
        - ls
    volumeMounts:
    - mountPath: /mysecret/secret
      name: mysecret
      readOnly: true
    resources:
      requests:
        cpu: 100m
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  volumes:
  - name: mysecret
    secret:
      secretName: mysecret
status: {}
