apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox-env
  name: busybox-env
spec:
  containers:
  - args:
    - env
    image: busybox
    imagePullPolicy: IfNotPresent
    name: busybox-env
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
