apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: sidecar
  name: sidecar
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - echo hello; sleep 3600
    image: busybox
    imagePullPolicy: IfNotPresent
    name: c1
    resources: {}

  - args:
    - /bin/sh
    - -c
    - echo hello; sleep 3600
    image: busybox
    imagePullPolicy: IfNotPresent
    name: c2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
