apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: sidecar
    run: service
  name: sidecar-service
spec:
  containers:
    - name: service
      image: busybox
      imagePullPolicy: IfNotPresent
      name: service
      command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']
    - name: sidecar
      image: busybox
      imagePullPolicy: IfNotPresent
      command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
