apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: bb
  name: bb
spec:
  replicas: 1
  selector:
    matchLabels:
      run: bb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: bb
    spec:
      containers:
      - args:
        - /bin/sh
        - -c
        - echo hello; sleep 3600
        image: busybox
        name: bb1
        resources: {}
      - args:
        - /bin/sh
        - -c
        - echo hello; sleep 3600
        image: busybox
        name: bb2
        resources: {}
status: {}
