apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: nginx4
  selfLink: /api/v1/namespaces/default/pods/nginx3
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: nginx4
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-r7b6n
      readOnly: true
  nodeSelector:
    accelerator: nvidia-tesla
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: docker-desktop
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-r7b6n
    secret:
      defaultMode: 420
      secretName: default-token-r7b6n
status:
  phase: Pending
  qosClass: BestEffort
