apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  labels:
    run: bbp
  name: bbp
spec:
  completions: 5
  parallelism: 5
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: bbp
    spec:
    
      containers:
      - args:
        - /bin/sh
        - -c
        - echo hello;sleep 30;echo world
        image: busybox
        name: bbp
        resources: {}
      restartPolicy: OnFailure
status: {}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  creationTimestamp: null
  labels:
    run: bb
  name: bb
spec:
  concurrencyPolicy: Allow
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
          labels:
            run: bb
        spec:
          containers:
          - args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
            image: busybox
            name: bb
            resources: {}
          restartPolicy: OnFailure
  schedule: '*/1 * * * *'
status: {}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  creationTimestamp: null
  labels:
    run: bb
  name: bb
spec:
  concurrencyPolicy: Allow
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
          labels:
            run: bb
        spec:
          containers:
          - args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
            image: busybox
            name: bb
            resources: {}
          restartPolicy: OnFailure
  schedule: '*/1 * * * *'
status: {}
