apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: node
  name: node
spec:
  containers:
  - image: nginx
    imagePullPolicy: IfNotPresent
    name: node
    resources: {}
  nodeSelector:
    accelerator: nvidia-tesla-p100
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
