apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  labels:
    run: hello
  name: hello
spec:
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: hello
    spec:
      containers:
      - args:
        - /bin/sh
        - -c
        - echo hello;sleep 30;echo world
        image: busybox
        name: hello
        resources: {}
      restartPolicy: OnFailure
  completions: 5
status: {}
