apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: 2019-05-13T12:43:07Z
  generateName: busyboxpod-69479fbd9c-
  labels:
    pod-template-hash: "2503596857"
    run: busyboxpod
  name: busyboxpod-69479fbd9c-kmdxq
  namespace: default
  ownerReferences:
  - apiVersion: extensions/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: busyboxpod-69479fbd9c
    uid: a8abe932-757c-11e9-afbf-025000000001
  resourceVersion: "743621"
  selfLink: /api/v1/namespaces/default/pods/busyboxpod-69479fbd9c-kmdxq
  uid: a8afc4f5-757c-11e9-afbf-025000000001
spec:
  containers:
  - command:
    - echo
    - hello
    image: busybox
    imagePullPolicy: Always
    name: busyboxpod
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-jd8nc
      readOnly: true
  dnsPolicy: ClusterFirst
  nodeName: docker-for-desktop
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-jd8nc
    secret:
      defaultMode: 420
      secretName: default-token-jd8nc
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2019-05-13T12:43:07Z
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: 2019-05-13T12:43:07Z
    message: 'containers with unready status: [busyboxpod]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: 2019-05-13T12:43:07Z
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://9fa30953bc549c2a18e8d47ecbc092f3b5276d98757f304723cdc39aa093f489
    image: busybox:latest
    imageID: docker-pullable://busybox@sha256:4b6ad3a68d34da29bf7c8ccb5d355ba8b4babcad1f99798204e7abb43e54ee3d
    lastState:
      terminated:
        containerID: docker://b0a4a8ab7256d85f27a2ebbffc61ebe7cd5f4fbab349844129bcbcbb58ffd847
        exitCode: 0
        finishedAt: 2019-05-13T12:43:32Z
        reason: Completed
        startedAt: 2019-05-13T12:43:32Z
    name: busyboxpod
    ready: false
    restartCount: 3
    state:
      terminated:
        containerID: docker://9fa30953bc549c2a18e8d47ecbc092f3b5276d98757f304723cdc39aa093f489
        exitCode: 0
        finishedAt: 2019-05-13T12:44:04Z
        reason: Completed
        startedAt: 2019-05-13T12:44:03Z
  hostIP: 192.168.65.3
  phase: Running
  podIP: 10.1.0.62
  qosClass: BestEffort
  startTime: 2019-05-13T12:43:07Z
