apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: 2019-05-13T12:50:13Z
  generateName: busyboxpod-fc7c5f987-
  labels:
    pod-template-hash: "973719543"
    run: busyboxpod
  name: busyboxpod-fc7c5f987-n5slk
  namespace: default
  ownerReferences:
  - apiVersion: extensions/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: busyboxpod-fc7c5f987
    uid: a69df0e8-757d-11e9-afbf-025000000001
  resourceVersion: "744222"
  selfLink: /api/v1/namespaces/default/pods/busyboxpod-fc7c5f987-n5slk
  uid: a6a3a603-757d-11e9-afbf-025000000001
spec:
  containers:
  - command:
    - bin/sh
    - -c
    - echo hello; sleep 3600
    image: busybox
    imagePullPolicy: Always
    name: busyboxpod
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-jd8nc
      readOnly: true
    
    image: busybox
    imagePullPolicy: Always
    name: busyboxpod2
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-jd8nc
      readOnly: true

  dnsPolicy: ClusterFirst
  nodeName: docker-for-desktop
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-jd8nc
    secret:
      defaultMode: 420
      secretName: default-token-jd8nc
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2019-05-13T12:50:13Z
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: 2019-05-13T12:50:18Z
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: 2019-05-13T12:50:13Z
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://f32a58f686ea17fa859320ae428315d0b08119de77463de392d2951afe73b0ad
    image: busybox:latest
    imageID: docker-pullable://busybox@sha256:4b6ad3a68d34da29bf7c8ccb5d355ba8b4babcad1f99798204e7abb43e54ee3d
    lastState: {}
    name: busyboxpod
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: 2019-05-13T12:50:17Z
  hostIP: 192.168.65.3
  phase: Running
  podIP: 10.1.0.66
  qosClass: BestEffort
  startTime: 2019-05-13T12:50:13Z
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  generateName: busyboxpod-fc7c5f987-
  labels:
    pod-template-hash: "973719543"
    run: busyboxpod
  ownerReferences:
  - apiVersion: extensions/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: busyboxpod-fc7c5f987
    uid: a69df0e8-757d-11e9-afbf-025000000001
  selfLink: /api/v1/namespaces/default/pods/busyboxpod-fc7c5f987-n5slk
spec:
  containers:
  - command:
    - bin/sh
    - -c
    - echo hello; sleep 3600
    image: busybox
    imagePullPolicy: Always
    name: busyboxpod
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-jd8nc
      readOnly: true
  dnsPolicy: ClusterFirst
  nodeName: docker-for-desktop
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-jd8nc
    secret:
      defaultMode: 420
      secretName: default-token-jd8nc
status:
  phase: Pending
  qosClass: BestEffort
