apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: nginx1
  selfLink: /api/v1/namespaces/default/pods/nginx1
spec:
  containers:
  - image: nginx
    imagePullPolicy: IfNotPresent
    name: nginx1
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-jd8nc
      readOnly: true
  nodeSelector:
    accelerator: nvidia-tesla-p100
  dnsPolicy: ClusterFirst
  nodeName: docker-for-desktop
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-jd8nc
    secret:
      defaultMode: 420
      secretName: default-token-jd8nc
status:
  phase: Pending
  qosClass: BestEffort
